# Generated by Django 5.1 on 2024-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0002_deal_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal_officer",
            name="pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/finaidbd/"
            ),
        ),
    ]
