# Generated by Django 5.1 on 2024-09-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0003_alter_deal_officer_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal_officer",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=1000)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("maxim_price", models.IntegerField()),
                ("monthly_pay", models.IntegerField()),
                ("is_accept", models.BooleanField(default=False)),
                ("final_price", models.IntegerField(blank=True, null=True)),
                ("mnthpay_final", models.IntegerField(blank=True, null=True)),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referenced_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refer",
                        to="finaidbd.deal_officer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid", models.IntegerField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("is_accpepted", models.BooleanField(default=False)),
                (
                    "orderer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="finaidbd.order",
                    ),
                ),
            ],
        ),
    ]
