# Generated by Django 5.1 on 2024-09-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0004_alter_deal_officer_pic_order_installment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="installment",
            old_name="is_accpepted",
            new_name="is_accepted",
        ),
    ]
