# Generated by Django 5.1 on 2024-09-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0005_rename_is_accpepted_installment_is_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="installment",
            name="due",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
