# Generated by Django 5.1 on 2024-09-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0006_installment_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installment",
            name="orderer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="finaidbd.order",
            ),
        ),
    ]
