# Generated by Django 5.1 on 2024-09-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0007_alter_installment_orderer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="installment",
            name="due",
        ),
        migrations.AddField(
            model_name="order",
            name="due",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
