# Generated by Django 5.1 on 2024-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finaidbd", "0008_remove_installment_due_order_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
